name: Build NDK for ARM64

on:
  workflow_dispatch:  # allows manual run

jobs:
  build-ndk:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 ninja-build cmake build-essential \
            openjdk-17-jdk wget unzip

      - name: Clone llvm_android
        run: |
          git clone https://android.googlesource.com/toolchain/llvm_android
          cd llvm_android
          # No need to checkout a specific branch; using the main branch
          # git checkout ndk-release-r26  # This line is no longer needed

      - name: Build LLVM for ARM64 host
        run: |
          cd llvm_android
          python3 toolchain/llvm_android/build.py

      - name: Clone NDK packaging scripts
        run: |
          git clone https://android.googlesource.com/platform/ndk
          cd ndk
          # Checkout the appropriate NDK version
          git checkout ndk-release-r26

      - name: Package NDK
        run: |
          cd ndk
          python3 package.py \
            --out /tmp/ndk-out \
            --toolchain-dir ../llvm_android/out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ndk-arm64-host
          path: /tmp/ndk-out
