name: Build Android NDK (x86_64 host → ARM64 target)

on:
  workflow_dispatch:

jobs:
  build-ndk:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Adjust as needed

    steps:
      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            git curl bison flex make pbzip2 texinfo uuid-runtime zip unzip \
            build-essential cmake ninja-build clang lld pkg-config libssl-dev \
            libncurses-dev ca-certificates wget openjdk-17-jdk \
            python3-distutils python3-venv python3-pip

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install Poetry
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install poetry

      - name: Install repo tool
        run: |
          sudo curl -fsSLo /usr/local/bin/repo \
            https://commondatastorage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo
          repo --version

      - name: Init AOSP manifest and sync NDK
        run: |
          mkdir aosp
          cd aosp
          repo init -u https://android.googlesource.com/platform/manifest -b master-ndk --partial-clone
          repo sync -j$(nproc) --no-clone-bundle

      - name: Install Python dependencies via Poetry
        run: |
          cd aosp/ndk
          poetry install --no-interaction
          poetry run python --version
          poetry run pip --version

      - name: Build and package NDK for ARM64 target
        run: |
          cd aosp/ndk
          # Use --arch=arm64 to cross-build for ARM64 target
          poetry run python checkbuild.py --no-build-tests --package --arch arm64 --jobs $(nproc)

      - name: List built artifacts
        run: |
          cd aosp/ndk
          echo "dist contents:"
          ls -lah dist || true
          echo "out contents (if present):"
          ls -lah out || true
          find . -type f -name "android-ndk-*.zip" -print || true

      - name: Upload packaged NDK artifact(s)
        uses: actions/upload-artifact@v4
        with:
          name: ndk-arm64
          path: |
            aosp/ndk/dist/*.zip
            aosp/ndk/out/**/*.zip
